services:
  hr-stt:
    build: ./services/hr-stt
    ports:
      - "8081:8081"
    environment:
      - MODEL_PATH=/models/whisper-large-v3-turbo-hr-parla-ctranslate2
      - DEVICE=cpu
      - COMPUTE_TYPE=int8
      - VAD_FILTER=true
      - CHUNK_SECONDS=1.0
    volumes:
      - ./models/whisper-large-v3-turbo-hr-parla-ctranslate2:/models/whisper-large-v3-turbo-hr-parla-ctranslate2:ro

  router:
    build: ./services/transcriber-router
    ports:
      - "3001:3001"
    environment:
      - DEEPGRAM_API_KEY=66579610c5761e3b93f727184c06819ffa326dfd
      - HR_STT_WSS=ws://hr-stt:8081/stream
      - HR_CONFIDENCE_LOCK=0.75
      - LANGLOCK_MS=2500
      - SECRET=optional_vapi_secret
    depends_on:
      - hr-stt
